version: '2'
services:
  nginx:
    image: openresty-docker-demo
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./nginx.conf.d/:/usr/local/openresty/nginx/conf/conf.d/
      - ./lua:/usr/local/openresty/nginx/lua
